### ISSUE TITLE
Build on Windows error -> `can't load .so/.DLL for: libopenblas.dll`

### ISSUE THREAD

**Issue by razvan-panda** [mikeizbicki/subhask#22]
I applied the hmatrix commits for `stack` and build on windows found in https://github.com/varosi/hmatrix/tree/feature/base-stack over the hmatrix 0.16.1.5 which is required as a subhask dependency. When I build only hmatrix it builds without any error.

Adding the altered hmatrix package above to the subhask package yaml configuration yields the following error:

```
$ stack build
subhask-0.1.1.0: build

--  While building package subhask-0.1.1.0 using:
      C:\\Users\\Razvan\\AppData\\Local\\Programs\\stack\\i386-windows\\ghc-7.10.2\\bin\\runhaskell.exe -package=Cabal-1.22.4.0 -clear-package-db -global-package-db -package-db=C:\Users\Razvan\AppData\Roaming\stack\snapshots\i386-windows\lts-3.3\7.10.2\pkgdb\ C:\Users\Razvan\AppData\Local\Temp\stack148160\Setup.hs --builddir=.stack-work\dist\i386-windows\Cabal-1.22.4.0\ build --ghc-options -hpcdir .stack-work\dist\i386-windows\Cabal-1.22.4.0\hpc\.hpc\
    Process exited with code: ExitFailure 1
    Logs have been written to: D:\Sources\subhask\.stack-work\logs\subhask-0.1.1.0.log

    Building subhask-0.1.1.0...
    Preprocessing library subhask-0.1.1.0...
    [ 6 of 36] Compiling SubHask.Mutable  ( src\SubHask\Mutable.hs, .stack-work\dist\i386-windows\Cabal-1.22.4.0\build\SubHask\Mutable.o )
    <command line>: can't load .so/.DLL for: libopenblas.dll (addDLL: could not load DLL)
    ghc.exe: libopenblas: The specified module could not be found.
```

The modified subhask yaml file used for building is:

```
flags:
  hmatrix:
    openblas: true
packages:
- '.'
- location: D:\Sources\hmatrix-varosi
  subdirs:
  - packages\base
extra-deps:
    [ gamma-0.9.0.2
    , continued-fractions-0.9.1.1
    , converge-0.1.0.1
    ]
resolver: lts-3.3

extra-include-dirs:
- D:\Libs\OpenBLAS\OpenBLAS-v0.2.14-Win64-int64\include
extra-lib-dirs:
- D:\Libs\OpenBLAS\OpenBLAS-v0.2.14-Win64-int64\lib
```

Could instead have passed the extra setting by command line as mentioned in: https://github.com/varosi/hmatrix/blob/feature/base-stack/INSTALL.md
